# This file was generated by GoReleaser. DO NOT EDIT.
cask "rexpose" do
  name "rexpose"
  desc ""
  homepage ""
  version "1.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rexpose"

  on_macos do
    url "https://github.com/rexpose/rexpose/releases/download/#{version}/rexpose_Darwin_all.tar.gz"
    sha256 "ef74154e4879f7a0104cbff71d441a6d329524844a941bdd7c1e48bfa5908d52"
  end

  on_linux do
    on_intel do
      url "https://github.com/rexpose/rexpose/releases/download/#{version}/rexpose_Linux_x86_64.tar.gz"
      sha256 "890d48a9fbd3b15119e94e510b7e7bee6363dbf9692265e0f7ed94f511411d85"
    end
    on_arm do
      url "https://github.com/rexpose/rexpose/releases/download/#{version}/rexpose_Linux_arm64.tar.gz"
      sha256 "b5f367023d1f95855819b1185d759138ff87be02f6b2eb9f33397401fe87ab4b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rexpose"]
    end
  end

  # No zap stanza required
end
