# This file was generated by GoReleaser. DO NOT EDIT.
cask "rexpose" do
  name "rexpose"
  desc ""
  homepage ""
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rexpose"

  on_macos do
    url "https://github.com/k4i6/rexpose/releases/download/#{version}/rexpose_Darwin_all.tar.gz"
    sha256 "83a99f2ac05785f6b950f2b0213fb675dc112755ce9621a02bc11d77c72f9869"
  end

  on_linux do
    on_intel do
      url "https://github.com/k4i6/rexpose/releases/download/#{version}/rexpose_Linux_x86_64.tar.gz"
      sha256 "371e3161a861c417f5714c1a170be6b8d1b3f51cee5d5880b757e0434421cfec"
    end
    on_arm do
      url "https://github.com/k4i6/rexpose/releases/download/#{version}/rexpose_Linux_arm64.tar.gz"
      sha256 "27b6120ac953f11678f72c321104699c9bce36dc46b0f3a6395ced52bd8c4c6b"
    end
  end

  # No zap stanza required
end
