# This file was generated by GoReleaser. DO NOT EDIT.
cask "rexpose" do
  name "rexpose"
  desc ""
  homepage ""
  version "1.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rexpose"

  on_macos do
    url "https://github.com/rexpose/rexpose/releases/download/#{version}/rexpose_Darwin_all.tar.gz"
    sha256 "dfe1856fdcea82f704bed4f136e6e9ab405a2aa136fac843a75b870b1a48dbcc"
  end

  on_linux do
    on_intel do
      url "https://github.com/rexpose/rexpose/releases/download/#{version}/rexpose_Linux_x86_64.tar.gz"
      sha256 "cfd9dccb248c4f30d1cba6025d7f41b97224756a143804d67f28e4b1e55b51fb"
    end
    on_arm do
      url "https://github.com/rexpose/rexpose/releases/download/#{version}/rexpose_Linux_arm64.tar.gz"
      sha256 "689f0d753819bc748651d6092e62066571e8da9976fd4c8b1a56848dcd2920b6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rexpose"]
    end
  end

  # No zap stanza required
end
